# Build as jupyterhub/singleuser
# Run with the DockerSpawner in JupyterHub

FROM jupyter/scipy-notebook

MAINTAINER Ian Allison <iana@pims.math.ca>

EXPOSE 8888

USER root
# fetch juptyerhub-singleuser entrypoint
RUN wget -q https://raw.githubusercontent.com/jupyterhub/jupyterhub/0.7.2/scripts/jupyterhub-singleuser -O /usr/local/bin/jupyterhub-singleuser && \
    chmod 755 /usr/local/bin/jupyterhub-singleuser

RUN apt-get update && apt-get install -y \
  build-essential \
  fonts-dejavu \
  python-dev \
  gfortran \
  libzmq5 \
  libzmq5-dev \
  libssl-dev \
  less openssh-client zip \
  man git libxrender1 \
  pyqt4-dev-tools \
  gnupg procps && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

# R
RUN conda config --add channels r && \
    conda install --quiet --yes \
    'r-base=3.3.2' \
    'r-irkernel=0.7*' \
    'r-plyr=1.8*' \
    'r-devtools=1.12*' \
    'r-dplyr=0.5*' \
    'r-ggplot2=2.2*' \
    'r-tidyr=0.6*' \
    'r-shiny=0.14*' \
    'r-rmarkdown=1.2*' \
    'r-forecast=7.3*' \
    'r-stringr=1.1*' \
    'r-rsqlite=1.1*' \
    'r-reshape2=1.4*' \
    'r-nycflights13=0.2*' \
    'r-caret=6.0*' \
    'r-rcurl=1.95*' \
    'r-crayon=1.3*' \
    'r-tidyverse' \
    'r-randomforest=4.6*' && conda clean -tipsy

RUN echo "deb http://www.deb-multimedia.org stretch main non-free" >> /etc/apt/sources.list
RUN apt-key adv --keyserver pgp.mit.edu --recv-keys 65558117
RUN apt-get update && apt-get install -y ffmpeg && apt-get clean && rm -rf /var/lib/apt/lists/*

USER jovyan

RUN conda install --yes pyqt \
  beautifulsoup4 \
  html5lib \
  mpld3 \
  gmaps \
  tensorflow \
  keras \
  atlas \
  lapack \
  nltk && \
  conda clean -tipsy

RUN conda install --yes -c damianavila82 rise && \
  conda clean -tipsy

ADD requirements.txt /tmp/requirements.txt
# And the stuff that isn't in anaconda
RUN pip install -r /tmp/requirements.txt

ADD Rprofile.site /opt/conda/lib/R/etc/Rprofile.site

RUN jupyter nbextension enable --py widgetsnbextension --sys-prefix

RUN jupyter labextension install @jupyterlab/google-drive

USER root

ADD pip.conf /etc/pip.conf

# Show Julia where conda libraries are
# Add essential packages
RUN apt-get update && apt-get -y install libhdf5-100 hdf5-tools && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN userdel jovyan
ENV SHELL /bin/bash

ADD systemuser.sh /srv/singleuser/systemuser.sh

CMD ["sh", "/srv/singleuser/systemuser.sh"]

RUN mkdir -p /opt/notebook/local_templates
ADD notebook.html /opt/notebook/local_templates/notebook.html
RUN mkdir -p /etc/jupyter
ADD jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py
